# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [2]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. What explains the datatype of the array?

In [21]:
# Integer array
my_array1 = np.array([1, 2, 3, 4])
print("Shape of my_array1:", my_array1.shape)
print("Data type of my_array1 elements:", my_array1.dtype)

# Mixed type array
my_array2 = np.array([1, "hello", 3])
print("\nShape of my_array2:", my_array2.shape)
print("Data type of my_array2 elements:", my_array2.dtype)
# Explanation: Mixing int and string promotes the entire array to strings (dtype '<U11').


Shape of my_array1: (4,)
Data type of my_array1 elements: int64

Shape of my_array2: (3,)
Data type of my_array2 elements: <U21


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [22]:
my_array3 = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", my_array3.shape)
print("Size:", my_array3.size)  # Total number of elements
print("Data type:", my_array3.dtype)


Shape: (2, 3)
Size: 6
Data type: int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [23]:
num_samples = 100
num_features = 17
tabular_data = np.random.random((num_samples, num_features))
print("Shape of tabular data:", tabular_data.shape)


Shape of tabular data: (100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [24]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

image_data = np.random.random((num_images, num_rows, num_cols, num_channels))
print("Shape of image data:", image_data.shape)

Shape of image data: (100, 256, 256, 3)


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over all the elements in the array. Print the output.

In [25]:
my_array4 = np.array([[1, 2], [3, 4], [5, 6]])
print("1. Shape:", my_array4.shape)

print("2. Total sum:", np.sum(my_array4))
print("3. Sum by column:", np.sum(my_array4, axis=0))
print("4. Sum by row (as float):", np.sum(my_array4, axis=1).astype(float))

print("5. First row:", my_array4[0])
print("6. Second row:", my_array4[1])
print("7. Element at (1, 0):", my_array4[1, 0])

my_array4[2, 1] = 10
print("8. Modified array:\n", my_array4)

print("9. Loop over elements:")
for row in my_array4:
    for val in row:
        print(val, end=' ')


1. Shape: (3, 2)
2. Total sum: 21
3. Sum by column: [ 9 12]
4. Sum by row (as float): [ 3.  7. 11.]
5. First row: [1 2]
6. Second row: [3 4]
7. Element at (1, 0): 3
8. Modified array:
 [[ 1  2]
 [ 3  4]
 [ 5 10]]
9. Loop over elements:
1 2 3 4 5 10 

You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [26]:
print("1.", np.random.rand(3, 2))
print("2.", np.arange(1991, 2018))
print("3.", np.zeros((3, 5, 10)))
print("4.", np.ones((3, 5, 10)))
print("5.", 5 * np.ones((2, 2)))
print("6.", np.random.normal(0, 1, 10))


1. [[0.38643974 0.40942165]
 [0.02320613 0.03671392]
 [0.30205873 0.95805644]]
2. [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
3. [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
4. [[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [9]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d (Hint: use np.reshape());
2. Convert the years_3d array to a flat 1D array. Call this array years_1d (Hint: use np.flatten());
3. Add a new dimension (axis=0) to the years_1d array. Call this array years_2d (Hint: use np.expand_dims());
4. Remove the first axis from years_2d array. Call this array years_1d (Hint: use np.squeeze()).

For each exercise print the array and its shape.

In [27]:
years = np.arange(1991, 2018)
print("Original shape:", years.shape)

years_3d = years.reshape((3, 3, 3))
print("1. 3D array:", years_3d.shape)

years_1d = years_3d.flatten()
print("2. Flattened array:", years_1d.shape)

years_2d = np.expand_dims(years_1d, axis=0)
print("3. Expanded dims:", years_2d.shape)

years_1d_again = np.squeeze(years_2d, axis=0)
print("4. Squeezed back:", years_1d_again.shape)


Original shape: (27,)
1. 3D array: (3, 3, 3)
2. Flattened array: (27,)
3. Expanded dims: (1, 27)
4. Squeezed back: (27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [28]:
# Concatenate examples
print("1.", np.concatenate((np.array([1, 2]), np.array([3, 4]))))
print("2.", np.concatenate((np.array([[1], [2]]), np.array([[3], [4]])), axis=1))
print("3.", np.concatenate((np.zeros((2,2)), np.ones((2,2))), axis=0))
print("4.", np.concatenate((np.arange(3), np.arange(3,6)), axis=0))

# Stack examples
print("5.", np.stack((np.array([1, 2]), np.array([3, 4]))))
print("6.", np.stack((np.ones(3), np.zeros(3)), axis=1))
print("7.", np.stack([np.arange(5)] * 3, axis=0))
print("8.", np.stack([np.full((2,), i) for i in range(3)], axis=0))


1. [1 2 3 4]
2. [[1 3]
 [2 4]]
3. [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]
4. [0 1 2 3 4 5]
5. [[1 2]
 [3 4]]
6. [[1. 0.]
 [1. 0.]
 [1. 0.]]
7. [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
8. [[0 0]
 [1 1]
 [2 2]]


---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [12]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [13]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [14]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [15]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [30]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[0.09937353, 0.84499208, 0.66970242, 0.96634253],
       [0.6866152 , 0.79079929, 0.59628123, 0.00668868],
       [0.38347787, 0.935465  , 0.06119359, 0.83823729],
       [0.7621429 , 0.59478823, 0.48583373, 0.18892897],
       [0.34150298, 0.7686633 , 0.45791553, 0.24110871],
       [0.84777789, 0.38403823, 0.29776958, 0.70828868],
       [0.27450515, 0.02413655, 0.78947195, 0.66621192],
       [0.05990369, 0.16631529, 0.77016755, 0.67081354],
       [0.1081097 , 0.63237205, 0.04045902, 0.21235379],
       [0.37371452, 0.76071898, 0.33424506, 0.2644446 ]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [31]:
my_array = np.random.random((10, 4))
print("Original shape:", my_array.shape)

mean = np.mean(my_array, axis=0, keepdims=True)
std = np.std(my_array, axis=0, keepdims=True)

standardized = (my_array - mean) / std
print("Standardized array:\n", standardized)
print("Shape:", standardized.shape)


Original shape: (10, 4)
Standardized array:
 [[-1.2192909   0.74491566  0.64995876 -0.77502365]
 [ 1.04140183  1.46075463 -0.7111337  -0.77492779]
 [ 1.47751842  0.105992   -0.43346204 -0.50703725]
 [-1.25761756  0.94683963 -1.10206576  1.82313821]
 [-0.25008869 -1.29109542  0.58623735  1.94896184]
 [ 0.60143093 -1.08625642  0.33919911 -0.66530919]
 [ 1.35758661 -1.3500561   0.69854648  0.12772136]
 [-0.08663725  0.05843884 -0.98634975 -0.91466815]
 [-0.87897855  1.11252857  2.10586711  0.079925  ]
 [-0.78532483 -0.70206138 -1.14679754 -0.34278039]]
Shape: (10, 4)


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [18]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [19]:
# YOUR CODE HERE